{
  "login": [
    { "id": 1, "email": "teste@gmail.com", "password": "123456", "name": "lucas" },
    {"id": 2, "email": "abcd@gmail.com", "password": "abcd", "name": "teste" }
  ],
  "admin": [
    { "id": 1, "email": "admin@gmail.com", "password": "admin", "name": "admin" }
  ]
}
